% Edited by M. Tavella <michele.tavella@epfl.ch> on 29/08/09 11:31:13
%
% function postprob = eegc2_bcidemo_classify(problem, buffer)
% 
% Where: postprob	vector with posterior probabilities [1 x classes]
% 
%        problem    structure created with eegc2_bcidemo_train
%        data       EEG window [points x channels]
% 
% Beware: if window size does not match [problem.dw x problem.numChs], 
%         an empty vector is returned

function [postprob, nfeature, afeature] = eegc3_smr_bci(analysis, buffer)

% Preprocess EEG
sample = eegc3_smr_preprocess(buffer, ...
	analysis.options.prep.dc, ...
	analysis.options.prep.car, ...  
	analysis.options.prep.laplacian, ...
	analysis.settings.prep.laplacian);

% Feature extraction based on feature selection
feature = eegc3_smr_features(sample, ...
	analysis.settings.eeg.fs, ...
	analysis.tools.features.bands, ...
	analysis.settings.features.psd.win, ...
	analysis.settings.features.psd.ovl, ...
	analysis.tools.features.channels);

if(nargout == 3)
    afeature = eegc3_smr_features(sample, ...
    	analysis.settings.eeg.fs, ...
        analysis.settings.features.psd.freqs, ...
    	analysis.settings.features.psd.win, ...
    	analysis.settings.features.psd.ovl, ...
    	1:analysis.settings.eeg.chs);
end

% Feature normalization
nfeature = eegc3_smr_npsd(feature');

% Classification
[activations postprob] = gauClassifier(...
	analysis.tools.net.gau.M, ...
	analysis.tools.net.gau.C, ...
	nfeature);

